version: '3.8'

services:
  nft-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - SOLANA_NETWORK=devnet
      # Add your configuration here
      - COLLECTION_ADDRESS=your_collection_address_here
      - WALLET_PRIVATE_KEY=your_wallet_private_key_here
    volumes:
      # Mount source code for development
      - ./src:/app/src
      # Mount environment file
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching if needed
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  redis_data:
